INDUSTRIES = {
    'Arts & Entertainment': [
        'Arts & Crafts-Materials & Supplies',
        'Art Galleries & Dealers',
        'Art Goods-Retail',
        'Artists-Fine Arts',
        'Audio-Visual Equipment & Supplies',
        'Entertainment Bureaus',
        'Music Instruction',
        'Sound Systems & Equipment'
    ],
    'Business & Professional Services': [
        'Carpet & Rug Cleaners',
        'Employment Agencies',
        'Freight Forwarding',
        'Movers & Storage Service',
        'Management Consultants',
        'Packaging Materials',
        'Secretarial Services',
        'Toilets-Washroom Hygiene Service'
    ],
    'Clothing & Accessories': [
        'Children\'s & Infants Wear-Retail',
        'Clothing',
        'Clothing Designers',
        'Clothing-Used',
        'Tee-Shirts',
        'Tee-Shirts-Printing',
        'Tee-Shirts-Wholesale & Manufacturers',
        'Uniforms',
        'Uniforms-Retail',
        'Uniforms-Wholesale & Manufacturers'
    ],
    'Computers & Electronics': [
        'Air Conditioning Equipment & Systems',
        'Air Conditioning Equipment & Systems-Repairing & Cleaning',
        'Computers',
        'Computer Accessories & Supplies',
        'Computer Networking',
        'Computer Software-Business Solution',
        'Computers Software Development & Packages',
        'Copying Machines & Supplies',
        'Printers',
        'Telecommunication Equipment & Supplies'
    ],
    'Construction': [
        'Air Conditioning Contractors',
        'Building Materials',
        'Constructions',
        'Contractors-Building, General',
        'Cranes',
        'Doors',
        'Engineering Works',
        'Electric Contractors',
        'Hardware-Wholesale',
        'Material Handling Equipment',
        'Stainless Steel'
    ],
    'Education': [
        'Aircraft Flying Schools',
        'Child Therapy/Learning Programs',
        'Educational Consultants',
        'Educational Aids',
        'Management Training & Development',
        'Schools-Academic-Colleges & Universities',
        'Schools-Academic-Elementary & Secondary',
        'Schools-Tailoring',
        'Schools-Fashion & Designing',
        'Tutoring'
    ],
    'Media & Communications': [
        'Advertising Agencies & Counsellors',
        'Advertising-Digital Printing',
        'Advertising-Outdoor',
        'Balloons',
        'Canopies-Renting',
        'Event Management Consultants',
        'Events Support Services',
        'Exhibitions-Display, Expositions & Trade Shows',
        'Signs',
        'Tents'
    ],
    'Food & Dining': [
        'Cafes',
        'Cafeterias',
        'Caterers',
        'Coffee Dealers-Wholesale',
        'Coffee Houses',
        'Food Ingredients & Additives',
        'Food Products',
        'Foods-Ready To Serve',
        'Restaurants',
        'Seafoods'
    ],
    'Health & Medicine': [
        'Clinics',
        'Dental Surgeons',
        'Dentists',
        'Health Care Products &/Or Services',
        'Hearing Aids',
        'Hospitals',
        'Hospital Equipment & Supplies',
        'Medical Practitioners Equipment & Supplies',
        'Medical Practitioners-Registered',
        'Safety Equipment & Clothing'
    ],
    'Home & Garden': [
        'Awnings & Canopies',
        'Carpet & Rug Dealers-New',
        'Cleaning Equipment',
        'Cleaning Service',
        'Fumigation',
        'Gates-Automatic',
        'Interior Decorators & Designers',
        'Kitchen Equipment & Supplies-Commercial',
        'Landscape Contractors',
        'Office Furniture & Equipment Dealers',
        'Pest Control',
        'Renovation-Office & Home',
        'Termite Control'
    ],
    'Industry & Agriculture': [
        'Aluminium',
        'Chemicals',
        'Machinery',
        'Oil & Gas Companies-Support Services',
        'Paper Products',
        'Plastic Products',
        'Plastics-Products (Finished)-Wholesale & Manufacturers',
        'Pumps-Manufacturers & Distributors',
        'Laboratory Equipment & Supplies',
        'Steel Products'
    ],
    'Legal & Finance': [
        'Accountants',
        'Accountants-Chartered',
        'Accounting-Services',
        'Accounting/Financial (Computer Software & Packages)',
        'Advocates & Solicitors',
        'Banks',
        'Insurance',
        'Lawyers',
        'Legal Support Services',
        'Tax Consultants'
    ],
    'Office Supplies': [
        'Cash Registers & Supplies',
        'Carpet & Rug Distributors & Manufacturers',
        'Document Storage',
        'Office Furniture & Equipment-Wholesale & Manufacturers',
        'Office Supplies',
        'Printing Equipment',
        'Racks',
        'Stationers Supplies',
        'Stationers-Retail',
        'Stationery-Wholesale'
    ],
    'Personal Care & Services': [
        'Barbers',
        'Beauty Aromatherapy',
        'Beauty Salons',
        'Beauty Salons-Slimming',
        'Cosmetic Supplies',
        'Hearing Care',
        'Massage-Traditional',
        'Physical Fitness',
        'Psychologists',
        'Reflexology'
    ],
    'Security Services': [
        'Burglar Alarm Systems',
        'Fire Protection Equipment',
        'Guard Dogs',
        'Guard & Patrol Service',
        'Locksmiths',
        'Safes & Vaults',
        'Security Consultants',
        'Security Control Equipment & Systems'
    ],
    'Shopping': [
        'Curtains-Retail',
        'Florists-Retail',
        'Gift Shops',
        'Hampers',
        'Premium Goods',
        'Shopping Centres',
        'Souvenirs-Wholesale & Manufacturers'
    ],
    'Travel & Transportation': [
        'Car Rental & Leasing',
        'Hotels (In Peninsular Malaysia)',
        'Hotel & Resorts',
        'Hotels (In Sabah & Sarawak)',
        'Hotel-Apartments & Suites',
        'Logistics',
        'Motorcar Renting & Leasing',
        'Resorts',
        'Tour Operators',
        'Tourist Attractions',
        'Transport Agents',
        'Transportation',
        'Travel Bureaus'
    ]
}

CITIES = (
    'Kuala Lumpur',
    'Shah Alam',
    'Petaling Jaya',
    'Subang Jaya',
    'Pulau Pinang',
    'Johor Bahru',
    'Pasir Gudang',
    'Kajang',
    'Cheras',
    'Ampang',
    'Klang',
    'Ipoh',
    'Batu Gajah',
    'Selayang',
    'Rawang',
    'Kuching',
    'Seremban',
    'Georgetown',
    'Malacca',
    'Kota Bahru',
    'Kota Kinabalu',
    'Kuantan',
    'Sungai Petani',
    'Batu Pahat',
    'Tawau',
    'Sandakan',
    'Bukit Mertajam',
    'Alor Setar',
    'Kuala Terengganu',
    'Taiping',
    'Miri',
    'Kluang',
    'Butterworth',
    'Kulim',
    'Kulai',
    'Sibu',
    'Muar',
    'Sitiawan',
    'Kangar',
    'Banting',
    'Jitra',
    'Sepang',
    'Kuala Selangor',
    'Teluk Intan',
    'Lahad Datu',
    'Bayan Lepas',
    'Kuala Kubu Bharu',
    'Kota Tinggi',
    'Segamat',
    'Pasir Mas',
    'Bintulu',
    'Alor Gajah',
    'Parit Buntar',
    'Tanjung Malim',
    'Tapah',
    'Keningau',
    'Chukai',
    'Nibong Tebal',
    'Sungai Jawi',
    'Temerioh',
)
